# Generated by Django 5.2.6 on 2025-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_careercategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tags_en',
            field=models.CharField(blank=True, help_text='Теги через запятую (английский)', max_length=500, verbose_name='Теги (английский)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags_kg',
            field=models.CharField(blank=True, help_text='Теги через запятую (кыргызский)', max_length=500, verbose_name='Теги (кыргызский)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags_ru',
            field=models.CharField(blank=True, help_text='Теги через запятую (русский)', max_length=500, verbose_name='Теги (русский)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую (устаревшее поле)', max_length=500, verbose_name='Теги (устаревшее)'),
        ),
    ]
