# Generated by Django 5.2.5 on 2025-09-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_event_location_remove_news_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/', verbose_name='Изображение объявления'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения объявления'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='Изображение события'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения события'),
        ),
    ]
