# Generated by Django 5.2.5 on 2025-09-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_image_fields_to_events_announcements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
    ]
