# Generated by Django 5.2.5 on 2025-09-15 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicregulationsection',
            name='regulation',
        ),
        migrations.RemoveField(
            model_name='academicregulationrule',
            name='section',
        ),
        migrations.DeleteModel(
            name='DownloadableDocument',
        ),
        migrations.RemoveField(
            model_name='exchangebenefit',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='guiderequirement',
            name='guide',
        ),
        migrations.AlterUniqueTogether(
            name='guidestep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='guidestep',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='guidestepdetail',
            name='step',
        ),
        migrations.RemoveField(
            model_name='internalruleitem',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='internshiprequirementitem',
            name='requirement',
        ),
        migrations.DeleteModel(
            name='MobilityRequirement',
        ),
        migrations.RemoveField(
            model_name='organizationspecialization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='universityprogram',
            name='university',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.AlterModelOptions(
            name='partnerorganization',
            options={'ordering': ['name_ru'], 'verbose_name': 'Организация-партнер', 'verbose_name_plural': 'Организации-партнеры'},
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentappeal',
            name='appeal_type',
        ),
        migrations.RemoveField(
            model_name='studentappeal',
            name='responded_at',
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание (кыргызский)'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='name_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Название (английский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='name_kg',
            field=models.CharField(default=1, max_length=255, verbose_name='Название (кыргызский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='name_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Название (русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentappeal',
            name='category',
            field=models.CharField(choices=[('academic', 'Академические вопросы'), ('administrative', 'Административные вопросы'), ('financial', 'Финансовые вопросы'), ('technical', 'Технические вопросы'), ('other', 'Другое')], default=1, max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentappeal',
            name='processed_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='studentappeal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='appeals/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Прикрепленный файл'),
        ),
        migrations.AlterField(
            model_name='studentappeal',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема обращения'),
        ),
        migrations.DeleteModel(
            name='AcademicRegulation',
        ),
        migrations.DeleteModel(
            name='AcademicRegulationRule',
        ),
        migrations.DeleteModel(
            name='AcademicRegulationSection',
        ),
        migrations.DeleteModel(
            name='ExchangeBenefit',
        ),
        migrations.DeleteModel(
            name='ExchangeOpportunity',
        ),
        migrations.DeleteModel(
            name='GuideRequirement',
        ),
        migrations.DeleteModel(
            name='StudentGuide',
        ),
        migrations.DeleteModel(
            name='GuideStep',
        ),
        migrations.DeleteModel(
            name='GuideStepDetail',
        ),
        migrations.DeleteModel(
            name='InternalRule',
        ),
        migrations.DeleteModel(
            name='InternalRuleItem',
        ),
        migrations.DeleteModel(
            name='InternshipRequirement',
        ),
        migrations.DeleteModel(
            name='InternshipRequirementItem',
        ),
        migrations.DeleteModel(
            name='OrganizationSpecialization',
        ),
        migrations.DeleteModel(
            name='PartnerUniversity',
        ),
        migrations.DeleteModel(
            name='UniversityProgram',
        ),
    ]
