# Generated by Django 5.2.5 on 2025-09-18 04:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0002_remove_academicregulationsection_regulation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('effective_date', models.DateField(verbose_name='Дата вступления в силу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Учебный регламент',
                'verbose_name_plural': 'Учебные регламенты',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название документа (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название документа (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название документа (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Файл документа')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (байты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ для скачивания',
                'verbose_name_plural': 'Документы для скачивания',
                'ordering': ['title_ru'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('type', models.CharField(choices=[('semester', 'Семестровый обмен'), ('year', 'Годовой обмен')], max_length=20, verbose_name='Тип обмена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Возможность обмена',
                'verbose_name_plural': 'Возможности обмена',
            },
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок шага (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок шага (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок шага (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаг инструкции',
                'verbose_name_plural': 'Шаги инструкций',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InternalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило внутреннего распорядка',
                'verbose_name_plural': 'Правила внутреннего распорядка',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InternshipRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('category', models.CharField(choices=[('academic', 'Академические требования'), ('documents', 'Документы для практики'), ('duration', 'Продолжительность практики')], max_length=20, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Требование к практике',
                'verbose_name_plural': 'Требования к практике',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MobilityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('category', models.CharField(choices=[('academic', 'Академические требования'), ('language', 'Языковые требования'), ('documents', 'Документы')], max_length=20, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Требование мобильности',
                'verbose_name_plural': 'Требования мобильности',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название университета (русский)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='Название университета (кыргызский)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название университета (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Университет-партнер',
                'verbose_name_plural': 'Университеты-партнеры',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название шаблона (русский)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='Название шаблона (кыргызский)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название шаблона (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('file', models.FileField(upload_to='report_templates/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'pdf'])], verbose_name='Файл шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Инструкция для студентов',
                'verbose_name_plural': 'Инструкции для студентов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRegulationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок раздела (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Заголовок раздела (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок раздела (английский)')),
                ('number', models.CharField(max_length=10, verbose_name='Номер раздела')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='student_life.academicregulation')),
            ],
            options={
                'verbose_name': 'Раздел регламента',
                'verbose_name_plural': 'Разделы регламентов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRegulationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Текст правила (русский)')),
                ('text_kg', models.TextField(verbose_name='Текст правила (кыргызский)')),
                ('text_en', models.TextField(verbose_name='Текст правила (английский)')),
                ('number', models.CharField(max_length=10, verbose_name='Номер правила')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='student_life.academicregulationsection')),
            ],
            options={
                'verbose_name': 'Правило регламента',
                'verbose_name_plural': 'Правила регламентов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Текст преимущества (русский)')),
                ('text_kg', models.TextField(verbose_name='Текст преимущества (кыргызский)')),
                ('text_en', models.TextField(verbose_name='Текст преимущества (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='student_life.exchangeopportunity')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GuideStepDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Текст детали (русский)')),
                ('text_kg', models.TextField(verbose_name='Текст детали (кыргызский)')),
                ('text_en', models.TextField(verbose_name='Текст детали (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='student_life.guidestep')),
            ],
            options={
                'verbose_name': 'Деталь шага',
                'verbose_name_plural': 'Детали шагов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InternalRuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Текст правила (русский)')),
                ('text_kg', models.TextField(verbose_name='Текст правила (кыргызский)')),
                ('text_en', models.TextField(verbose_name='Текст правила (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='student_life.internalrule')),
            ],
            options={
                'verbose_name': 'Элемент правила',
                'verbose_name_plural': 'Элементы правил',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InternshipRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Текст (русский)')),
                ('text_kg', models.TextField(verbose_name='Текст (кыргызский)')),
                ('text_en', models.TextField(verbose_name='Текст (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='student_life.internshiprequirement')),
            ],
            options={
                'verbose_name': 'Элемент требования',
                'verbose_name_plural': 'Элементы требований',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название специализации (русский)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='Название специализации (кыргызский)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название специализации (английский)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='student_life.partnerorganization')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.AddField(
            model_name='guidestep',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='student_life.studentguide'),
        ),
        migrations.CreateModel(
            name='GuideRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Текст требования (русский)')),
                ('text_kg', models.TextField(verbose_name='Текст требования (кыргызский)')),
                ('text_en', models.TextField(verbose_name='Текст требования (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='student_life.studentguide')),
            ],
            options={
                'verbose_name': 'Требование инструкции',
                'verbose_name_plural': 'Требования инструкций',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название программы (русский)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='Название программы (кыргызский)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название программы (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание программы (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание программы (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание программы (английский)')),
                ('duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('language', models.CharField(max_length=100, verbose_name='Язык обучения')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='student_life.partneruniversity')),
            ],
            options={
                'verbose_name': 'Программа обмена',
                'verbose_name_plural': 'Программы обмена',
            },
        ),
    ]
