# Generated by Django 5.2.5 on 2025-09-21 06:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0003_academicregulation_downloadabledocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название альбома (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название альбома (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название альбома (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('cover_image', models.ImageField(upload_to='photo_albums/covers/', verbose_name='Обложка альбома')),
                ('tags_ru', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (русский)')),
                ('tags_kg', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (кыргызский)')),
                ('tags_en', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (английский)')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['-event_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentLifeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ru', models.CharField(max_length=255, verbose_name='Название показателя (русский)')),
                ('label_kg', models.CharField(max_length=255, verbose_name='Название показателя (кыргызский)')),
                ('label_en', models.CharField(max_length=255, verbose_name='Название показателя (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('type', models.CharField(choices=[('clubs', 'Клубы и организации'), ('events', 'Мероприятия'), ('photos', 'Фотографии'), ('videos', 'Видео'), ('students', 'Активные студенты'), ('achievements', 'Достижения')], max_length=20, verbose_name='Тип статистики')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Статистика студенческой жизни',
                'verbose_name_plural': 'Статистика студенческой жизни',
                'ordering': ['order', 'type'],
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название видео (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название видео (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название видео (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'wmv'])], verbose_name='Видеофайл')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo и т.д.', verbose_name='Ссылка на видео')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/', verbose_name='Превью видео')),
                ('tags_ru', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (русский)')),
                ('tags_kg', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (кыргызский)')),
                ('tags_en', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (английский)')),
                ('type', models.CharField(choices=[('event', 'Мероприятие'), ('interview', 'Интервью'), ('tutorial', 'Обучающее видео'), ('announcement', 'Объявление'), ('documentary', 'Документальное')], max_length=20, verbose_name='Тип видео')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Продолжительность')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Видеоконтент',
                'verbose_name_plural': 'Видеоконтент',
                'ordering': ['-created_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Название фото (русский)')),
                ('title_kg', models.CharField(blank=True, max_length=255, verbose_name='Название фото (кыргызский)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Название фото (английский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(blank=True, verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (английский)')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('tags_ru', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (русский)')),
                ('tags_kg', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (кыргызский)')),
                ('tags_en', models.TextField(blank=True, help_text='Разделяйте запятыми', verbose_name='Теги (английский)')),
                ('photographer', models.CharField(blank=True, max_length=255, verbose_name='Фотограф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='student_life.photoalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
