# Generated by Django 5.2.5 on 2025-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0004_photoalbum_studentlifestatistic_videocontent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, help_text='Ссылка на внешнее изображение (альтернатива загрузке файла)', null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Изображение'),
        ),
    ]
