# Generated by Django 5.2.5 on 2025-09-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0005_photo_url_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Ссылка на внешнее превью (альтернатива загрузке файла)', null=True, verbose_name='URL превью'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Превью видео'),
        ),
    ]
