# Generated by Django 5.2.5 on 2025-09-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0006_videocontent_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание шага (английский)'),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание шага (кыргызский)'),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание шага (русский)'),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='step_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер шага'),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='timeframe_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время выполнения (английский)'),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='timeframe_kg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время выполнения (кыргызский)'),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='timeframe_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время выполнения (русский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='category',
            field=models.CharField(choices=[('academic', 'Академические вопросы'), ('administrative', 'Административные вопросы'), ('documents', 'Документы и справки'), ('financial', 'Финансовые вопросы'), ('appeals', 'Заявления и обращения')], default='academic', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='contact_info_en',
            field=models.TextField(blank=True, verbose_name='Контактная информация (английский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='contact_info_kg',
            field=models.TextField(blank=True, verbose_name='Контактная информация (кыргызский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='contact_info_ru',
            field=models.TextField(blank=True, verbose_name='Контактная информация (русский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='estimated_time_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ориентировочное время (английский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='estimated_time_kg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ориентировочное время (кыргызский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='estimated_time_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ориентировочное время (русский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='icon',
            field=models.CharField(choices=[('CalendarDaysIcon', 'Календарь'), ('UserGroupIcon', 'Группа пользователей'), ('ClipboardDocumentListIcon', 'Список документов'), ('DocumentTextIcon', 'Документ'), ('AcademicCapIcon', 'Академическая шапочка'), ('BuildingOfficeIcon', 'Офисное здание')], default='DocumentTextIcon', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='max_duration_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальный срок (английский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='max_duration_kg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальный срок (кыргызский)'),
        ),
        migrations.AddField(
            model_name='studentguide',
            name='max_duration_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальный срок (русский)'),
        ),
    ]
