# Generated by Django 5.2.5 on 2025-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0007_guidestep_description_en_guidestep_description_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип или фото организации-партнера', null=True, upload_to='partner_organizations/', verbose_name='Логотип'),
        ),
    ]
