# Generated by Django 5.2.5 on 2025-10-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_life', '0008_partnerorganization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (русский)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='Название (кыргызский)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (английский)')),
                ('icon', models.CharField(default='📚', max_length=100, verbose_name='Иконка')),
                ('color', models.CharField(default='from-blue-500 to-blue-600', max_length=100, verbose_name='Цвет градиента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория электронных ресурсов',
                'verbose_name_plural': 'Категории электронных ресурсов',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='EResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (русский)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название (кыргызский)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (английский)')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('description_kg', models.TextField(verbose_name='Описание (кыргызский)')),
                ('description_en', models.TextField(verbose_name='Описание (английский)')),
                ('icon', models.CharField(default='🔗', max_length=100, verbose_name='Иконка')),
                ('color', models.CharField(default='from-blue-500 to-blue-600', max_length=100, verbose_name='Цвет градиента')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL ресурса')),
                ('users_count', models.PositiveIntegerField(default=0, verbose_name='Количество пользователей')),
                ('status', models.CharField(choices=[('online', 'В сети'), ('maintenance', 'Техническое обслуживание'), ('offline', 'Офлайн')], default='online', max_length=20, verbose_name='Статус')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eresources', to='student_life.eresourcecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Электронный ресурс',
                'verbose_name_plural': 'Электронные ресурсы',
                'ordering': ['order', 'title_ru'],
            },
        ),
        migrations.CreateModel(
            name='EResourceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.CharField(max_length=255, verbose_name='Текст (русский)')),
                ('text_kg', models.CharField(max_length=255, verbose_name='Текст (кыргызский)')),
                ('text_en', models.CharField(max_length=255, verbose_name='Текст (английский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='student_life.eresource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Особенность ресурса',
                'verbose_name_plural': 'Особенности ресурсов',
                'ordering': ['order'],
            },
        ),
    ]
