# Generated by Django 5.2.5 on 2025-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, help_text='Полный адрес партнера', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='Бишкек', help_text='Город расположения партнера', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city_en',
            field=models.CharField(blank=True, help_text='City name in English', max_length=100, verbose_name='City (English)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city_ky',
            field=models.CharField(blank=True, help_text='City name in Kyrgyz', max_length=100, verbose_name='Шаар (Кыргызча)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='cooperation_since',
            field=models.PositiveIntegerField(blank=True, help_text='Год начала сотрудничества', null=True, verbose_name='Сотрудничество с'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(default='Кыргызстан', help_text='Страна расположения партнера', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country_en',
            field=models.CharField(blank=True, help_text='Country name in English', max_length=100, verbose_name='Country (English)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country_ky',
            field=models.CharField(blank=True, help_text='Country name in Kyrgyz', max_length=100, verbose_name='Өлкө (Кыргызча)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, help_text='Контактный email партнера', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='partner',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Год основания организации-партнера', null=True, verbose_name='Год основания'),
        ),
        migrations.AddField(
            model_name='partner',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS координата широты (например: 42.8746)', max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='partner',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS координата долготы (например: 74.5698)', max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('clinical', 'Клиническая база'), ('university', 'Университет'), ('organization', 'Организация'), ('business', 'Бизнес-партнер'), ('academic', 'Академический партнер')], default='academic', help_text='Категория партнера', max_length=20, verbose_name='Тип партнера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partnership_areas',
            field=models.TextField(blank=True, help_text='Области сотрудничества через запятую', verbose_name='Области сотрудничества'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, help_text='Контактный телефон партнера', max_length=20, verbose_name='Телефон'),
        ),
    ]
