# Generated by Django 5.2.5 on 2025-09-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0002_partner_address_partner_city_partner_city_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('clinical', '🏥 Клинические базы'), ('university', '🎓 Университеты'), ('organization', '🔬 Организации'), ('business', '💼 Бизнес-партнеры'), ('academic', '📚 Академические')], default='academic', help_text='Категория партнера', max_length=20, verbose_name='Тип партнера'),
        ),
    ]
