# Generated by Django 5.2.5 on 2025-09-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0003_alter_partner_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(help_text='Название достижения на русском языке', max_length=300, verbose_name='Заголовок (Русский)')),
                ('title_en', models.CharField(blank=True, help_text='Achievement title in English', max_length=300, verbose_name='Title (English)')),
                ('title_ky', models.CharField(blank=True, help_text='Achievement title in Kyrgyz', max_length=300, verbose_name='Аталышы (Кыргызча)')),
                ('description_ru', models.TextField(help_text='Подробное описание достижения на русском языке', verbose_name='Описание (Русский)')),
                ('description_en', models.TextField(blank=True, help_text='Achievement description in English', verbose_name='Description (English)')),
                ('description_ky', models.TextField(blank=True, help_text='Achievement description in Kyrgyz', verbose_name='Сүрөттөмө (Кыргызча)')),
                ('year', models.PositiveIntegerField(help_text='Год получения достижения', verbose_name='Год')),
                ('category', models.CharField(choices=[('education', 'Образование'), ('science', 'Наука'), ('international', 'Международное сотрудничество'), ('infrastructure', 'Инфраструктура'), ('awards', 'Награды'), ('research', 'Исследования'), ('innovation', 'Инновации')], help_text='Категория достижения', max_length=20, verbose_name='Категория')),
                ('icon', models.CharField(default='🏆', help_text='Emoji иконка для отображения', max_length=10, verbose_name='Иконка')),
                ('icon_color', models.CharField(choices=[('bg-yellow-500', 'Желтый'), ('bg-red-500', 'Красный'), ('bg-blue-500', 'Синий'), ('bg-purple-500', 'Фиолетовый'), ('bg-green-500', 'Зеленый'), ('bg-emerald-500', 'Изумрудный'), ('bg-indigo-500', 'Индиго'), ('bg-pink-500', 'Розовый'), ('bg-orange-500', 'Оранжевый'), ('bg-teal-500', 'Бирюзовый')], default='bg-yellow-500', help_text='CSS класс цвета иконки', max_length=20, verbose_name='Цвет иконки')),
                ('featured', models.BooleanField(default=False, help_text='Отображать как основное достижение', verbose_name='Рекомендуемое')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать достижение на сайте', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-featured', '-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(help_text='Полное имя основателя на русском языке', max_length=200, verbose_name='Имя (Русский)')),
                ('name_en', models.CharField(blank=True, help_text='Full name in English', max_length=200, verbose_name='Name (English)')),
                ('name_ky', models.CharField(blank=True, help_text='Full name in Kyrgyz', max_length=200, verbose_name='Аты (Кыргызча)')),
                ('position_ru', models.CharField(help_text='Должность основателя на русском языке', max_length=300, verbose_name='Должность (Русский)')),
                ('position_en', models.CharField(blank=True, help_text='Position in English', max_length=300, verbose_name='Position (English)')),
                ('position_ky', models.CharField(blank=True, help_text='Position in Kyrgyz', max_length=300, verbose_name='Кызматы (Кыргызча)')),
                ('years', models.CharField(blank=True, help_text='Например: 1995-2005', max_length=50, verbose_name='Период деятельности')),
                ('image', models.ImageField(blank=True, help_text='Фотография основателя', null=True, upload_to='founders/', verbose_name='Фотография')),
                ('description_ru', models.TextField(help_text='Биография основателя на русском языке', verbose_name='Описание (Русский)')),
                ('description_en', models.TextField(blank=True, help_text='Biography in English', verbose_name='Description (English)')),
                ('description_ky', models.TextField(blank=True, help_text='Biography in Kyrgyz', verbose_name='Сүрөттөмө (Кыргызча)')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='JSON структура с достижениями на разных языках', verbose_name='Достижения')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок отображения основателей', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать основателя на сайте', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='UniversityStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(help_text='Название статистики на русском языке', max_length=200, verbose_name='Название (Русский)')),
                ('name_en', models.CharField(blank=True, help_text='Statistic name in English', max_length=200, verbose_name='Name (English)')),
                ('name_ky', models.CharField(blank=True, help_text='Statistic name in Kyrgyz', max_length=200, verbose_name='Аталышы (Кыргызча)')),
                ('value', models.CharField(help_text='Числовое значение статистики', max_length=20, verbose_name='Значение')),
                ('unit', models.CharField(blank=True, help_text='Например: %, +, штук', max_length=10, verbose_name='Единица измерения')),
                ('icon', models.CharField(default='📊', help_text='Emoji иконка для отображения', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать статистику на сайте', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статистика университета',
                'verbose_name_plural': 'Статистика университета',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.CharField(default='🤝', help_text='Эмодзи иконка партнера (например: 🏥, 🌐)', max_length=10, verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='FounderAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_ru', models.TextField(help_text='Описание достижения на русском языке', verbose_name='Достижение (Русский)')),
                ('achievement_en', models.TextField(blank=True, help_text='Achievement description in English', verbose_name='Achievement (English)')),
                ('achievement_ky', models.TextField(blank=True, help_text='Achievement description in Kyrgyz', verbose_name='Жетишкендик (Кыргызча)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок сортировки')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_set', to='about_section.founder', verbose_name='Основатель')),
            ],
            options={
                'verbose_name': 'Достижение основателя',
                'verbose_name_plural': 'Достижения основателей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(help_text='Название подразделения на русском языке', max_length=200, verbose_name='Название (Русский)')),
                ('name_en', models.CharField(blank=True, help_text='Department name in English', max_length=200, verbose_name='Name (English)')),
                ('name_ky', models.CharField(blank=True, help_text='Department name in Kyrgyz', max_length=200, verbose_name='Аталышы (Кыргызча)')),
                ('head_name_ru', models.CharField(blank=True, help_text='ФИО руководителя на русском языке', max_length=200, verbose_name='Руководитель (Русский)')),
                ('head_name_en', models.CharField(blank=True, help_text='Head name in English', max_length=200, verbose_name='Head (English)')),
                ('head_name_ky', models.CharField(blank=True, help_text='Head name in Kyrgyz', max_length=200, verbose_name='Башчы (Кыргызча)')),
                ('structure_type', models.CharField(choices=[('leadership', 'Руководство'), ('faculties', 'Факультеты'), ('administrative', 'Административные подразделения'), ('support', 'Вспомогательные подразделения')], help_text='Категория организационной структуры', max_length=20, verbose_name='Тип подразделения')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('icon', models.CharField(default='🏢', help_text='Emoji иконка для отображения', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать подразделение на сайте', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='about_section.organizationstructure', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Организационная структура',
                'verbose_name_plural': 'Организационная структура',
                'ordering': ['structure_type', 'order', 'name_ru'],
            },
        ),
    ]
