# Generated by Django 5.2.6 on 2025-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0003_alter_partner_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.CharField(default='🤝', help_text='Эмодзи иконка партнера (например: 🏥, 🌐)', max_length=10, verbose_name='категория'),
        ),
    ]
