# Generated by Django 5.2.5 on 2025-10-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0004_achievement_founder_universitystatistic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityFounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(help_text='Полное имя основателя на русском языке', max_length=200, verbose_name='Имя (Русский)')),
                ('name_en', models.CharField(blank=True, help_text='Full name in English', max_length=200, verbose_name='Name (English)')),
                ('name_ky', models.CharField(blank=True, help_text='Full name in Kyrgyz', max_length=200, verbose_name='Аты (Кыргызча)')),
                ('position_ru', models.CharField(help_text='Должность основателя на русском языке', max_length=300, verbose_name='Должность (Русский)')),
                ('position_en', models.CharField(blank=True, help_text='Position in English', max_length=300, verbose_name='Position (English)')),
                ('position_ky', models.CharField(blank=True, help_text='Position in Kyrgyz', max_length=300, verbose_name='Кызмат орду (Кыргызча)')),
                ('years_ru', models.CharField(blank=True, help_text='Период работы на русском языке (например: 1995-2010)', max_length=100, verbose_name='Годы службы (Русский)')),
                ('years_en', models.CharField(blank=True, help_text='Period of service in English', max_length=100, verbose_name='Years of Service (English)')),
                ('years_ky', models.CharField(blank=True, help_text='Service period in Kyrgyz', max_length=100, verbose_name='Кызмат жылдары (Кыргызча)')),
                ('image', models.ImageField(blank=True, help_text='Фотография основателя', null=True, upload_to='founders/', verbose_name='Фотография')),
                ('description_ru', models.TextField(help_text='Подробное описание основателя на русском языке', verbose_name='Описание (Русский)')),
                ('description_en', models.TextField(blank=True, help_text='Detailed description in English', verbose_name='Description (English)')),
                ('description_ky', models.TextField(blank=True, help_text='Detailed description in Kyrgyz', verbose_name='Сүрөттөө (Кыргызча)')),
                ('achievements_ru', models.JSONField(blank=True, default=list, help_text='Список достижений на русском языке (JSON массив)', verbose_name='Достижения (Русский)')),
                ('achievements_en', models.JSONField(blank=True, default=list, help_text='List of achievements in English (JSON array)', verbose_name='Achievements (English)')),
                ('achievements_ky', models.JSONField(blank=True, default=list, help_text='List of achievements in Kyrgyz (JSON array)', verbose_name='Жетишкендиктер (Кыргызча)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (чем меньше число, тем выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать основателя на сайте', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Основатель университета',
                'verbose_name_plural': 'Основатели университета',
                'ordering': ['order', 'name_ru'],
            },
        ),
    ]
