# Generated by Django 5.2.5 on 2025-10-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0005_universityfounder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founderachievement',
            name='founder',
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
        migrations.DeleteModel(
            name='FounderAchievement',
        ),
    ]
