# Generated by Django 5.2.5 on 2025-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0005_accreditation_counciltype_councilmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilmember',
            name='name_en',
            field=models.CharField(blank=True, help_text='Full name in English', max_length=200, verbose_name='Full Name (English)'),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='name_ky',
            field=models.CharField(blank=True, help_text='Full name in Kyrgyz', max_length=200, verbose_name='Аты-жөнү (Кыргызча)'),
        ),
    ]
