# Generated by Django 5.2.6 on 2025-10-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_section', '0006_councilmember_name_en_councilmember_name_ky'),
        ('about_section', '0006_remove_old_founder_models'),
    ]

    operations = [
    ]
