# Generated by Django 5.2.6 on 2025-09-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='ФИО (русский)')),
                ('full_name_kg', models.CharField(max_length=255, verbose_name='ФИО (кыргызский)')),
                ('full_name_en', models.CharField(max_length=255, verbose_name='ФИО (английский)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Должность (русский)')),
                ('position_kg', models.CharField(max_length=255, verbose_name='Должность (кыргызский)')),
                ('position_en', models.CharField(max_length=255, verbose_name='Должность (английский)')),
                ('bio_ru', models.TextField(verbose_name='Биография (русский)')),
                ('bio_kg', models.TextField(verbose_name='Биография (кыргызский)')),
                ('bio_en', models.TextField(verbose_name='Биография (английский)')),
                ('photo', models.ImageField(upload_to='teachers/photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
