# Generated by Django 5.2.6 on 2025-09-12 04:43

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='ФИО (русский)')),
                ('full_name_kg', models.CharField(blank=True, max_length=255, verbose_name='ФИО (кыргызский)')),
                ('full_name_en', models.CharField(blank=True, max_length=255, verbose_name='ФИО (английский)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Должность (русский)')),
                ('position_kg', models.CharField(blank=True, max_length=255, verbose_name='Должность (кыргызский)')),
                ('position_en', models.CharField(blank=True, max_length=255, verbose_name='Должность (английский)')),
                ('bio_ru', models.TextField(blank=True, verbose_name='Биография (русский)')),
                ('bio_kg', models.TextField(blank=True, verbose_name='Биография (кыргызский)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Биография (английский)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='management/photos/', verbose_name='Фото')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='teachers.management', verbose_name='Вышестоящий')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководство',
            },
        ),
    ]
