# Generated by Django 5.2.5 on 2025-09-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_coverage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaarticle',
            name='official_site_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на официальный сайт'),
        ),
    ]
