# Generated by Django 5.2.5 on 2025-09-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('foundational', 'Учредительные документы'), ('academic', 'Учебная деятельность'), ('administrative', 'Административная деятельность'), ('research', 'Научная деятельность')], max_length=50, unique=True, verbose_name='Категория')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Название (KG)')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Название (KG)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(verbose_name='Описание (EN)')),
                ('description_kg', models.TextField(verbose_name='Описание (KG)')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл документа')),
                ('file_size', models.CharField(blank=True, max_length=20, verbose_name='Размер файла')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order', '-updated_at'],
            },
        ),
    ]
