# Generated by Django 5.2.5 on 2025-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='social_media_link',
            field=models.URLField(blank=True, help_text='Link to club social media page (Telegram, Instagram, etc.)', max_length=500, null=True, verbose_name='Social Media Link'),
        ),
    ]
