# Generated by Django 5.2.5 on 2025-10-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_opportunities', '0002_club_social_media_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='social_media_link',
            field=models.URLField(blank=True, help_text='Link to event social media page (Telegram, Instagram, etc.)', max_length=500, null=True, verbose_name='Social Media Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='social_media_link',
            field=models.URLField(blank=True, help_text='Link to project social media page (Telegram, Instagram, etc.)', max_length=500, null=True, verbose_name='Social Media Link'),
        ),
    ]
