# Generated by Django 5.2.5 on 2025-09-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfacility',
            name='capacity_en',
            field=models.CharField(default=100, max_length=100, verbose_name='Вместимость (англ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingfacility',
            name='capacity_kg',
            field=models.CharField(default=100, max_length=100, verbose_name='Вместимость (кырг)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingfacility',
            name='capacity_ru',
            field=models.CharField(default=199, max_length=100, verbose_name='Вместимость (рус)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingfacility',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вместимость (устар.)'),
        ),
    ]
