# Generated by Django 5.2.5 on 2025-09-29 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_buildingfacility_capacity_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Название (кырг)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (англ)')),
                ('icon', models.CharField(default='🏫', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория аудитории',
                'verbose_name_plural': 'Категории аудиторий',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название (кырг)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (англ)')),
                ('description_ru', models.TextField(verbose_name='Краткое описание (рус)')),
                ('description_kg', models.TextField(verbose_name='Краткое описание (кырг)')),
                ('description_en', models.TextField(verbose_name='Краткое описание (англ)')),
                ('full_description_ru', models.TextField(verbose_name='Полное описание (рус)')),
                ('full_description_kg', models.TextField(verbose_name='Полное описание (кырг)')),
                ('full_description_en', models.TextField(verbose_name='Полное описание (англ)')),
                ('stage', models.CharField(choices=[('seed', 'Посевная стадия'), ('series_a', 'Серия A'), ('growth', 'Рост'), ('research', 'Исследования'), ('prototype', 'Прототип'), ('scaling', 'Масштабирование')], max_length=20, verbose_name='Стадия')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('development', 'В разработке'), ('scaling', 'Масштабирование'), ('research', 'Исследования'), ('prototype', 'Прототип')], max_length=20, verbose_name='Статус')),
                ('funding', models.CharField(max_length=50, verbose_name='Финансирование')),
                ('year', models.CharField(max_length=4, verbose_name='Год основания')),
                ('image', models.CharField(default='🚀', max_length=10, verbose_name='Эмодзи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Стартап',
                'verbose_name_plural': 'Стартапы',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='StartupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('name_kg', models.CharField(max_length=100, verbose_name='Название (кырг)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (англ)')),
                ('icon', models.CharField(default='🚀', max_length=10, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория стартапа',
                'verbose_name_plural': 'Категории стартапов',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название (кырг)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (англ)')),
                ('description_ru', models.TextField(verbose_name='Описание (рус)')),
                ('description_kg', models.TextField(verbose_name='Описание (кырг)')),
                ('description_en', models.TextField(verbose_name='Описание (англ)')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('floor', models.CharField(max_length=10, verbose_name='Этаж')),
                ('size', models.PositiveIntegerField(verbose_name='Размер (м²)')),
                ('image', models.CharField(default='🏫', max_length=10, verbose_name='Эмодзи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='infrastructure.classroomcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название оборудования (рус)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название оборудования (кырг)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название оборудования (англ)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='infrastructure.classroom', verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Оборудование аудитории',
                'verbose_name_plural': 'Оборудование аудиторий',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название особенности (рус)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название особенности (кырг)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название особенности (англ)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='infrastructure.classroom', verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Особенность аудитории',
                'verbose_name_plural': 'Особенности аудиторий',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='StartupAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_ru', models.CharField(max_length=300, verbose_name='Достижение (рус)')),
                ('achievement_kg', models.CharField(max_length=300, verbose_name='Достижение (кырг)')),
                ('achievement_en', models.CharField(max_length=300, verbose_name='Достижение (англ)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='infrastructure.startup', verbose_name='Стартап')),
            ],
            options={
                'verbose_name': 'Достижение стартапа',
                'verbose_name_plural': 'Достижения стартапов',
                'ordering': ['order', 'achievement_ru'],
            },
        ),
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='infrastructure.startupcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='StartupInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название инвестора (рус)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Название инвестора (кырг)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название инвестора (англ)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='infrastructure.startup', verbose_name='Стартап')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='StartupTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя участника (рус)')),
                ('name_kg', models.CharField(max_length=200, verbose_name='Имя участника (кырг)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя участника (англ)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='infrastructure.startup', verbose_name='Стартап')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
                'ordering': ['order', 'name_ru'],
            },
        ),
    ]
