# Generated by Django 5.2.5 on 2025-09-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_commission_journalissue_scientificcouncil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='application_url',
            field=models.URLField(blank=True, help_text='Внешняя ссылка для подачи заявки на грант', verbose_name='Ссылка для подачи заявки'),
        ),
    ]
