# Generated by Django 5.2.5 on 2025-10-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='historymilestone',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='historymilestone',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='achievements_subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='approach_text_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='approach_title_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='future_text_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='future_title_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='impact_text_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='impact_title_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='mission_text_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='vision_text_ru',
        ),
        migrations.RemoveField(
            model_name='missionsection',
            name='vision_title_ru',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='value',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='value',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='label',
            field=models.CharField(help_text='Описание достижения на русском языке', max_length=200, verbose_name='Подпись (RU)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='label_en',
            field=models.CharField(blank=True, default='hello', help_text='Описание достижения на английском языке', max_length=200, verbose_name='Подпись (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='label_ky',
            field=models.CharField(blank=True, default='hello', help_text='Описание достижения на кыргызском языке', max_length=200, verbose_name='Подпись (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historymilestone',
            name='description',
            field=models.TextField(help_text='Подробное описание исторической вехи на русском языке', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='historymilestone',
            name='description_en',
            field=models.TextField(blank=True, default='hello', help_text='Подробное описание исторической вехи на английском языке', verbose_name='Описание (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historymilestone',
            name='description_ky',
            field=models.TextField(blank=True, default='hello', help_text='Подробное описание исторической вехи на кыргызском языке', verbose_name='Описание (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historymilestone',
            name='title',
            field=models.CharField(help_text='Название исторической вехи на русском языке', max_length=200, verbose_name='Заголовок вехи (RU)'),
        ),
        migrations.AlterField(
            model_name='historymilestone',
            name='title_en',
            field=models.CharField(blank=True, default='hello', help_text='Название исторической вехи на английском языке', max_length=200, verbose_name='Заголовок вехи (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historymilestone',
            name='title_ky',
            field=models.CharField(blank=True, default='hello', help_text='Название исторической вехи на кыргызском языке', max_length=200, verbose_name='Заголовок вехи (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='achievements_subtitle',
            field=models.TextField(blank=True, help_text='Описание под заголовком достижений на русском языке', verbose_name='Подзаголовок достижений (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='achievements_subtitle_en',
            field=models.TextField(blank=True, default='hello', help_text='Описание под заголовком достижений на английском языке', verbose_name='Подзаголовок достижений (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='achievements_subtitle_ky',
            field=models.TextField(blank=True, default='hello', help_text='Описание под заголовком достижений на кыргызском языке', verbose_name='Подзаголовок достижений (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='approach_text',
            field=models.TextField(help_text='Описание подхода университета на русском языке', verbose_name='Текст подхода (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='approach_text_en',
            field=models.TextField(blank=True, default='hello', help_text='Описание подхода университета на английском языке', verbose_name='Текст подхода (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='approach_text_ky',
            field=models.TextField(blank=True, default='hello', help_text='Описание подхода университета на кыргызском языке', verbose_name='Текст подхода (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='approach_title',
            field=models.CharField(default='Наш подход', max_length=200, verbose_name='Заголовок подхода (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='approach_title_en',
            field=models.CharField(blank=True, default='Our Approach', max_length=200, verbose_name='Заголовок подхода (EN)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='approach_title_ky',
            field=models.CharField(blank=True, default='Биздин мамиле', max_length=200, verbose_name='Заголовок подхода (KY)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='future_text',
            field=models.TextField(help_text='Описание перспектив развития на русском языке', verbose_name='Текст перспектив (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='future_text_en',
            field=models.TextField(blank=True, default='hello', help_text='Описание перспектив развития на английском языке', verbose_name='Текст перспектив (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='future_text_ky',
            field=models.TextField(blank=True, default='hello', help_text='Описание перспектив развития на кыргызском языке', verbose_name='Текст перспектив (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='future_title',
            field=models.CharField(default='Перспективы развития', max_length=200, verbose_name='Заголовок перспектив (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='future_title_en',
            field=models.CharField(blank=True, default='Future Prospects', max_length=200, verbose_name='Заголовок перспектив (EN)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='future_title_ky',
            field=models.CharField(blank=True, default='Өнүгүү келечектери', max_length=200, verbose_name='Заголовок перспектив (KY)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='impact_text',
            field=models.TextField(help_text='Описание вклада университета на русском языке', verbose_name='Текст вклада (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='impact_text_en',
            field=models.TextField(blank=True, default='hello', help_text='Описание вклада университета на английском языке', verbose_name='Текст вклада (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='impact_text_ky',
            field=models.TextField(blank=True, default='hello', help_text='Описание вклада университета на кыргызском языке', verbose_name='Текст вклада (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='impact_title',
            field=models.CharField(default='Наш вклад', max_length=200, verbose_name='Заголовок вклада (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='impact_title_en',
            field=models.CharField(blank=True, default='Our Impact', max_length=200, verbose_name='Заголовок вклада (EN)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='impact_title_ky',
            field=models.CharField(blank=True, default='Биздин салымыбыз', max_length=200, verbose_name='Заголовок вклада (KY)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='mission_text',
            field=models.TextField(help_text='Основной текст миссии университета на русском языке', verbose_name='Текст миссии (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='mission_text_en',
            field=models.TextField(blank=True, default='hello', help_text='Основной текст миссии университета на английском языке', verbose_name='Текст миссии (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='mission_text_ky',
            field=models.TextField(blank=True, default='hello', help_text='Основной текст миссии университета на кыргызском языке', verbose_name='Текст миссии (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Описание под заголовком на русском языке', verbose_name='Подзаголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='subtitle_en',
            field=models.TextField(blank=True, default='hello', help_text='Описание под заголовком на английском языке', verbose_name='Подзаголовок (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='subtitle_ky',
            field=models.TextField(blank=True, default='hello', help_text='Описание под заголовком на кыргызском языке', verbose_name='Подзаголовок (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='title',
            field=models.CharField(help_text='Основной заголовок секции миссии на русском языке', max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='title_en',
            field=models.CharField(blank=True, default='hello', help_text='Основной заголовок секции миссии на английском языке', max_length=200, verbose_name='Заголовок (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='title_ky',
            field=models.CharField(blank=True, default='hello', help_text='Основной заголовок секции миссии на кыргызском языке', max_length=200, verbose_name='Заголовок (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='vision_text',
            field=models.TextField(help_text='Описание видения университета на русском языке', verbose_name='Текст видения (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='vision_text_en',
            field=models.TextField(blank=True, default='hello', help_text='Описание видения университета на английском языке', verbose_name='Текст видения (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='vision_text_ky',
            field=models.TextField(blank=True, default='hello', help_text='Описание видения университета на кыргызском языке', verbose_name='Текст видения (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='vision_title',
            field=models.CharField(default='Наше видение', max_length=200, verbose_name='Заголовок видения (RU)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='vision_title_en',
            field=models.CharField(blank=True, default='Our Vision', max_length=200, verbose_name='Заголовок видения (EN)'),
        ),
        migrations.AlterField(
            model_name='missionsection',
            name='vision_title_ky',
            field=models.CharField(blank=True, default='Биздин көрүү', max_length=200, verbose_name='Заголовок видения (KY)'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='text',
            field=models.TextField(help_text='Описание приоритета на русском языке', verbose_name='Текст приоритета (RU)'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='text_en',
            field=models.TextField(blank=True, default='hello', help_text='Описание приоритета на английском языке', verbose_name='Текст приоритета (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priority',
            name='text_ky',
            field=models.TextField(blank=True, default='hello', help_text='Описание приоритета на кыргызском языке', verbose_name='Текст приоритета (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.TextField(help_text='Подробное описание ценности на русском языке', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='value',
            name='description_en',
            field=models.TextField(blank=True, default='hello', help_text='Подробное описание ценности на английском языке', verbose_name='Описание (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='description_ky',
            field=models.TextField(blank=True, default='hello', help_text='Подробное описание ценности на кыргызском языке', verbose_name='Описание (KY)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='title',
            field=models.CharField(help_text='Название ценности на русском языке', max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='value',
            name='title_en',
            field=models.CharField(blank=True, default='hello', help_text='Название ценности на английском языке', max_length=200, verbose_name='Заголовок (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='value',
            name='title_ky',
            field=models.CharField(blank=True, default='hello', help_text='Название ценности на кыргызском языке', max_length=200, verbose_name='Заголовок (KY)'),
            preserve_default=False,
        ),
    ]
