# Generated by Django 5.2.5 on 2025-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HSMInfo',
        ),
        migrations.DeleteModel(
            name='LearningGoal',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
