# Generated by Django 5.2.5 on 2025-09-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0002_delete_hsminfo_delete_learninggoal_delete_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='academic_degree_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ученая степень (EN)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic_degree_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ученая степень (KG)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ученое звание (EN)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic_title_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ученое звание (KG)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность (EN)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='position_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность (KG)'),
        ),
    ]
