# Generated by Django 5.2.5 on 2025-09-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0003_faculty_academic_degree_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='accreditation_type_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип аккредитации (EN)'),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='accreditation_type_kg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип аккредитации (KG)'),
        ),
    ]
