# Generated by Django 5.2.5 on 2025-09-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0004_accreditation_accreditation_type_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('name_kg', models.CharField(blank=True, max_length=200, verbose_name='ФИО (KG)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='ФИО (EN)')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('position_kg', models.CharField(blank=True, max_length=200, verbose_name='Должность (KG)')),
                ('position_en', models.CharField(blank=True, max_length=200, verbose_name='Должность (EN)')),
                ('degree', models.CharField(max_length=200, verbose_name='Ученая степень')),
                ('degree_kg', models.CharField(blank=True, max_length=200, verbose_name='Ученая степень (KG)')),
                ('degree_en', models.CharField(blank=True, max_length=200, verbose_name='Ученая степень (EN)')),
                ('experience', models.CharField(max_length=100, verbose_name='Опыт работы')),
                ('experience_kg', models.CharField(blank=True, max_length=100, verbose_name='Опыт работы (KG)')),
                ('experience_en', models.CharField(blank=True, max_length=100, verbose_name='Опыт работы (EN)')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('bio_kg', models.TextField(blank=True, verbose_name='Биография (KG)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Биография (EN)')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='Достижения')),
                ('achievements_kg', models.JSONField(blank=True, default=list, verbose_name='Достижения (KG)')),
                ('achievements_en', models.JSONField(blank=True, default=list, verbose_name='Достижения (EN)')),
                ('department', models.CharField(choices=[('directorate', 'Дирекция'), ('study_department', 'Учебный отдел'), ('science_department', 'Научный отдел'), ('therapy', 'Кафедра терапии'), ('surgery', 'Кафедра хирургии'), ('pediatrics', 'Кафедра педиатрии'), ('neurology', 'Кафедра неврологии'), ('dentistry', 'Кафедра стоматологии')], max_length=50, verbose_name='Департамент')),
                ('department_kg', models.CharField(blank=True, max_length=200, verbose_name='Департамент (KG)')),
                ('department_en', models.CharField(blank=True, max_length=200, verbose_name='Департамент (EN)')),
                ('specialization', models.TextField(blank=True, verbose_name='Специализация')),
                ('specialization_kg', models.TextField(blank=True, verbose_name='Специализация (KG)')),
                ('specialization_en', models.TextField(blank=True, verbose_name='Специализация (EN)')),
                ('staff_count', models.CharField(blank=True, max_length=100, verbose_name='Количество сотрудников')),
                ('staff_count_kg', models.CharField(blank=True, max_length=100, verbose_name='Количество сотрудников (KG)')),
                ('staff_count_en', models.CharField(blank=True, max_length=100, verbose_name='Количество сотрудников (EN)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, upload_to='leadership/photos/', verbose_name='Фото')),
                ('leadership_type', models.CharField(choices=[('director', 'Директор'), ('deputy_director', 'Заместитель директора'), ('department_head', 'Заведующий кафедрой'), ('dean', 'Декан'), ('vice_dean', 'Заместитель декана')], max_length=20, verbose_name='Тип руководства')),
                ('is_director', models.BooleanField(default=False, verbose_name='Является директором')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководство',
                'ordering': ['order', 'name'],
            },
        ),
    ]
