# Generated by Django 5.2.5 on 2025-09-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0005_leadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Департамент(RU)'),
        ),
    ]
