# Generated by Django 5.2.5 on 2025-10-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0007_qualityadvantage_qualitydocument_qualityprinciple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='bio_kg',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='staff_count',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='staff_count_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='staff_count_kg',
        ),
        migrations.AlterField(
            model_name='qualityprinciple',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание принципа (английский)'),
        ),
        migrations.AlterField(
            model_name='qualityprinciple',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание принципа (кыргызский)'),
        ),
        migrations.AlterField(
            model_name='qualityprinciple',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название принципа (английский)'),
        ),
        migrations.AlterField(
            model_name='qualityprinciple',
            name='title_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название принципа (кыргызский)'),
        ),
    ]
