# Generated by Django 5.2.5 on 2025-10-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm', '0008_remove_leadership_bio_remove_leadership_bio_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='bio_en',
            field=models.TextField(blank=True, verbose_name='Биография (EN)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='bio_kg',
            field=models.TextField(blank=True, verbose_name='Биография (KG)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='staff_count',
            field=models.CharField(blank=True, max_length=100, verbose_name='Количество сотрудников'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='staff_count_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Количество сотрудников (EN)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='staff_count_kg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Количество сотрудников (KG)'),
        ),
    ]
